force-app/main/default/objects/Loyalty_Customer__c/Loyalty_Customer__c.object-meta.xml
<CustomObject>
    <label>Loyalty Customer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Loyalty Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Customers</relationshipLabel>
    <relationshipName>Loyalty_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LoyaltyClass.cls
public with sharing class LoyaltyClass {
    public LoyaltyClass() {
        
    }
    public static void LoyaltytriggerHelperValidation(List<Loyalty_Customer__c> loyaltyContect) {
        for(Loyalty_Customer__c c : loyaltyContect){
            if(c.Account__c == null){
                c.addError('Must include a Account');
            }
            if(c.Date_of_Birth__c == null){
                c.addError('Must include a Date of Birth');
            }
            
            
         //   c.Origin = 'Web';
         //   update c;
          }
    }


}